[MPLUGIN-104] Bumping the maven-reporting-impl dependency to the fixed version of 2.0.4, which avoids the NoSuchMethodError in AbstractMavenReport when attempting to use the Renderer implementation to create a new sink (method was removed after -alpha-7 of doxia, from what I can tell).
git-svn-id: https://svn.apache.org/repos/asf/maven/plugin-tools/trunk@639778 13f79535-47bb-0310-9956-ffa450edef68